# Generated by Django 6.0.9 on 2026-10-09 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="nome"),
                ),
            ],
            options={
                "verbose_name": "característica",
                "db_table": "pets_tag",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="nome")),
                (
                    "species",
                    models.CharField(
                        choices=[("dog", "Cachorro"), ("cat", "Gato")],
                        max_length=8,
                        verbose_name="espécie",
                    ),
                ),
            ],
            options={
                "verbose_name": "raça",
                "db_table": "pets_breed",
                "ordering": ("species", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("species", "name"), name="pets_breed_unique_per_species"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PetModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "species",
                    models.CharField(
                        choices=[("dog", "Cachorro"), ("cat", "Gato")],
                        max_length=8,
                        verbose_name="espécie",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Macho"), ("female", "Fêmea")],
                        max_length=8,
                        verbose_name="sexo",
                    ),
                ),
                ("description", models.TextField(verbose_name="descrição")),
                ("city", models.CharField(max_length=100, verbose_name="cidade")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="estado",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=11, verbose_name="telefone de contato"),
                ),
                (
                    "photo",
                    models.ImageField(
                        max_length=200, upload_to="pets/", verbose_name="foto"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(db_index=True, verbose_name="publicado em"),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pets",
                        to="pets.breed",
                        verbose_name="raça",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pets",
                        to="pets.tag",
                        verbose_name="características",
                    ),
                ),
            ],
            options={
                "verbose_name": "pet",
                "db_table": "pets_pet",
                "ordering": ("-published_at",),
                "indexes": [
                    models.Index(fields=["state", "city"], name="pets_pet_location_idx")
                ],
            },
        ),
    ]
