# Generated by Django 6.0.9 on 2026-10-09 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionRequestModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("message", models.TextField(blank=True, verbose_name="mensagem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando resposta"),
                            ("approved", "Aprovado"),
                            ("rejected", "Recusado"),
                            ("withdrawn", "Cancelado"),
                        ],
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                ("requested_at", models.DateTimeField(verbose_name="pedido em")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decidido em"
                    ),
                ),
                (
                    "adopter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_requests",
                        to="pets.petmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido de adoção",
                "verbose_name_plural": "pedidos de adoção",
                "db_table": "adoption_request",
                "ordering": ("requested_at",),
                "indexes": [
                    models.Index(
                        fields=["pet", "status"], name="adoption_pet_status_idx"
                    ),
                    models.Index(
                        fields=["adopter", "status"], name="adoption_adopter_status_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["pending", "approved", "rejected", "withdrawn"],
                            )
                        ),
                        name="adoption_status_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("decided_at__isnull", True), ("status", "pending")
                            ),
                            models.Q(
                                models.Q(("status", "pending"), _negated=True),
                                ("decided_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="adoption_decided_when_final",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "approved")),
                        fields=("pet",),
                        name="adoption_one_approval_per_pet",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["approved", "pending", "rejected"])
                        ),
                        fields=("pet", "adopter"),
                        name="adoption_one_live_request_per_adopter",
                    ),
                ],
            },
        ),
    ]
