# Generated by Django 4.1.7 on 2023-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='nome_estado',
        ),
        migrations.AddField(
            model_name='estado',
            name='nome',
            field=models.CharField(default='AC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='sigla',
            field=models.CharField(default='Acre', max_length=2),
            preserve_default=False,
        ),
    ]
