# Generated by Django 4.1.7 on 2023-04-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='uf',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.estado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
