# Generated by Django 4.1.7 on 2023-04-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_user_bairro_user_cep_user_cidade_user_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.estado', to_field='sigla'),
        ),
    ]
