# Generated by Django 4.1.7 on 2023-04-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_estado_nome_alter_estado_sigla_alter_user_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.estado', to_field='nome'),
        ),
    ]
