# Generated by Django 4.1.7 on 2023-04-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_user_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descricao',
            field=models.TextField(default='Gostoso e maravilhoso', verbose_name='descricao'),
            preserve_default=False,
        ),
    ]
