# Generated by Django 4.1.7 on 2023-04-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_user_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uf',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.estado', to_field='nome'),
        ),
    ]
