# Generated by Django 4.1.7 on 2023-04-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0004_alter_pet_raca_alter_pet_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='telefone',
            new_name='tel',
        ),
    ]
