# Generated by Django 4.1.7 on 2023-04-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('AG', 'Aguardando aprovação'), ('AP', 'Aprovado'), ('R', 'Recusado')], default='AG', max_length=2)),
            ],
        ),
    ]
