# Generated by Django 4.1.7 on 2023-04-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adotar', '0001_initial'),
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoadocao',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='divulgar.pet'),
        ),
    ]
